---
title: "README"
author: "Shirley Robinson"
date: "18 May 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

## Objective of Assignment

The objective of this assignment is to demonstrate ability to collect, work with, and clean a data set. The goal is to prepare tidy data that can be used for later analysis. 

## Review Criteria

(1) The submitted data set is tidy.
(2) The Github repo contains the required scripts. 
(3) GitHub contains a code book that modifies and updates the available codebooks with the data to indicate all the variables and summaries calculated, along with units, and any other relevant information. 
(4) The README (this file) that explains the analysis files is clear and understandable.
(5) The work submitted for this project is the work of the student who submitted it.

## Background information on the data in the assignment

The data in the assignment represents the data collected from the accelerometers from the Samsung Galaxy S smartphone, in respect of wearable computing and is referenced as Human Activity Recognition using Smartphones.  A full description is available at the site where the data was obtained:

http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones

## Data for the assignment

The data for the assignment are available at: https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip

## Assignment tasks and requirements

The assignment required the creation of a single R script called run_analysis.R that:

(1) Merges the training and the test sets to create one data set.
(2) Extracts only the measurements on the mean and standard deviation for each measurement.
(3) Uses descriptive activity names to name the activities in the data set. 
(4) Appropriately labels the data set with descriptive variable names.
(5) From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.

## The Codebook 

The Codebook describing variables, the data, and any transformations or work that you performed to clean up the data called CodeBook.md is included in the GitHub repository 

## The R script 

The R script called run_analysis.R is embedded below and included in the GitHub repository.


```

## Downloading the data

temp <- tempfile()
download.file("https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip", temp)
unz(temp,"UCI HARdataset")
unlink(temp)

## Load dplyr package
library(dplyr)

   
## Assigning the datasets
features <- read.table("UCI HAR Dataset/features.txt", col.names = c("Feature_no.","Feature_name"))
activities <- read.table("UCI HAR Dataset/activity_labels.txt", col.names = c("code", "Activity_type"))
subject_test <- read.table("UCI HAR Dataset/test/subject_test.txt", col.names = "subject")
x_test <- read.table("UCI HAR Dataset/test/X_test.txt", col.names = features$Feature_name)
y_test <- read.table("UCI HAR Dataset/test/y_test.txt", col.names = "code")
subject_train <- read.table("UCI HAR Dataset/train/subject_train.txt", col.names = "subject")
x_train <- read.table("UCI HAR Dataset/train/X_train.txt", col.names = features$Feature_name)
y_train <- read.table("UCI HAR Dataset/train/y_train.txt", col.names = "code")

## Merging the data sets
X_set<- rbind(x_train, x_test)
Y_labels<- rbind(y_train, y_test)
subject_set<- rbind(subject_train, subject_test)
merged_data<- cbind(subject_set, Y_labels, X_set)

## Extracts only the mean and std deviation for each measurement
TidyData<- select(merged_data, subject, code, contains("mean"), contains("std"))


## Uses descriptive activity names to name the activities in the data set
TidyData$code <- activities[TidyData$code, 2]

## Appropriately labels the data set with descriptive variable names
names(TidyData)[1] = "Subject"
names(TidyData)[2] = "Activity"
names(TidyData)<- gsub("Acc", "Accelerator", names(TidyData))
names(TidyData)<- gsub("Gyro", "Gyroscope", names(TidyData))
names(TidyData)<- gsub ("BodyBody", "Body", names(TidyData))
names(TidyData)<- gsub ("Mag", "Magnitude", names(TidyData))
names(TidyData)<- gsub ("^t", "Time", names(TidyData))
names(TidyData)<- gsub ("^f", "Frequency", names(TidyData))
names(TidyData)<- gsub ("tBody", "TimeBody", names(TidyData))
names(TidyData)<- gsub ("mean", "MeanValue", names(TidyData))

## From the extracted data, creates a second, independent tidy data set with the average of each variable for each activity and each subject.
TidyData_gr<- group_by(TidyData, Subject, Activity)
TidyData2<- summarise_all(TidyData_gr, funs(mean)) 



```
## Final Tidy data set

TidyData2 is the final tidy data set that exports the data in a tidy data set manner after going through all the steps set out in the R script run_analysis.R above
